### ISSUE TITLE
adapt/reduce content in /weitersagen

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#10]
* which share-options do we want to keep?
  * adapt text for sharing with friends
* keep "termine" and link to c3w events?
* keep "abonnieren" and link to c3w public subscribe?

**Comment by pascoda** [comment]
* drop "mitmachen" ?
* drop "bilder teilen" ?

**Comment by eest9** [comment]
Wir benötigen "Teilen"-Texte für Twitter, E-Mail sowie Facebook. Also konkret dafür wenn mensch auf den Link klickt, welcher Defaulttext auf Anwender*innen-Seite vorgeschlagen werden soll.

**Comment by pascoda** [comment]
[entrance to the rabbit hole for "share on mastodon"](https://github.com/mastodon/mastodon/issues/442)

**Comment by eest9** [comment]
Entweder wir lösen das Problem mit der "CSRF-Verifizierung" für die Eintragung auf c3w public, oder wir ändern es schlicht auf einen Link zu https://lists.c3w.at/postorius/lists/public.lists.c3w.at/ (Nachteil → ein weiterer step für die Anmeldung)

**Comment by cambid** [comment]
> [entrance to the rabbit hole for "share on mastodon"](https://github.com/mastodon/mastodon/issues/442)

this is fixed in #23

**Comment by pascoda** [comment]
* link-texte korrigieren
* spenden-text überdenken
* button umfärben
* "Was kann ich noch machen?" statt "wie kann ich helfen"
