### ISSUE TITLE
burger menu not usable

### ISSUE THREAD

**Issue by KillerLink** [c3wien/Poke-That-Gmeind#100]
When reducing the browser window width, the top navigation folds to a burger menu in the top right.
Moving the mouse over the burger menu shows a list of the navigation entries.
Attempting to select one of the navigation entries with the mouse seems not possible, because as soon as the mouse leaves the burger menu the list with navigation entries vanishes.

OS: Linux, Browser: Chromium 102

**Comment by KillerLink** [comment]
here is a short video of the issue 

[burgerissue.webm](https://user-images.githubusercontent.com/17423668/178962907-35562bbe-424b-4ef2-ac60-81a5bca367a4.webm)

**Comment by cambid** [comment]
Thanks for bringing this up. We deployed a fix for this.
