### ISSUE TITLE
adapt/reduce content in /faq

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#11]
pretty much self-explanatory.

**Comment by pascoda** [comment]
* CSS: make speech bubbles same width, move more to center?
* check Qs and As.
* statt href zu /kontakt E-Mail-Adresse hinschreiben.
* wir speichern und verarbeiten name und email-adresse und kontaktierte gemeinde(n) und geben name und email-adresse an die gemeinde(n) weiter.
* wir möchen Einwohner*innen und Bürger*innen von Österreich

**Comment by pascoda** [comment]
only part that is still not resolved is speech bubble width.

additional discovery: color scheme is not being used.

**Comment by cambid** [comment]
This is solved with #71
