### ISSUE TITLE
post-mail pages layout

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#113]
visual style elements (buttons, arrows) and text clash w.r.t. alignment - buttons and arrows are centered while text is aligned left (with different paddings none the less :sweat_smile: )

![Screenshot 2022-07-18 at 15-38-26 Luftfilterbegehren](https://user-images.githubusercontent.com/6959763/179530623-d283c8c5-5767-4df9-93d1-4fc7daa44499.png)

IMO, all items should be centered to have a coherent layout.

**Comment by cambid** [comment]
hab das direkt deployed
