### ISSUE TITLE
[cities] Hinweis auf möglicherweise inkorrekte Daten

### ISSUE THREAD

**Issue by devNan0** [c3wien/Poke-That-Gmeind#118]
Das `cities.json` ist nicht zu 100% korrekt.

Ggf. sollte das in einen Hinweis irgendwo erwähnt werden.

Beispiele die ich jetzt mal auf die schnelle gefunden habe:
**Parndorf - 10717**
https://github.com/c3wien/Poke-That-Gmeind/blob/e05a05dea3ce1b91430634161b79e976995e3642/luftfilterbegehren/data/cities.json#L1109
Diese E-Mail ist von der Werbeagentur, richtig wäre: `post@parndorf.bgld.gv.at`

**Gattendorf - 10706**
https://github.com/c3wien/Poke-That-Gmeind/blob/e05a05dea3ce1b91430634161b79e976995e3642/luftfilterbegehren/data/cities.json#L988-L989
Hier stimmt weder URL noch E-Mail.
Richtige URL wäre `gattendorf.at` da `gemeinde-gattendorf.at` anscheinend nicht mehr verwendet wird.
E-Mail-Adresse ist vom ISP Kabelplus richtig wäre `buergerservice@gattendorf.bgld.gv.at`

**Comment by eest9** [comment]
Eventuell auch an https://github.com/bresu/oe_gemeinden melden?

**Comment by bresu** [comment]
> Eventuell auch an https://github.com/bresu/oe_gemeinden melden?

Danke, habe erst von eurem Projekt mitbekommen. Bin gerade dabei die Daten zu cleanen und zu verifizieren!

**Comment by cambid** [comment]
> Danke, habe erst jetzt von eurem Projekt mitbekommen. Bin gerade dabei die Daten zu cleanen und zu verifizieren!

Uh, sehr spannend. Können wir irgendwie helfen? Gibt es vielleicht den Quellcode (z. B. des ursprünglichen Scrapers oder anderes) irgendwo online?

**Comment by bresu** [comment]
> > Danke, habe erst jetzt von eurem Projekt mitbekommen. Bin gerade dabei die Daten zu cleanen und zu verifizieren!
> 
> Uh, sehr spannend. Können wir irgendwie helfen? Gibt es vielleicht den Quellcode (z. B. des ursprünglichen Scrapers oder anderes) irgendwo online?

Scraper hab ich damals nicht auf Github geteilt, finde ihn jetzt auch gerade nicht. 
Ich hab mir damals einfach mit der Statistik Austria Ortschaften-Liste lauter Domains gebaut und die durch iteriert.
Werde jetzt einen Scraper bauen der [gemeinde-oesterreich.at]( https://www.gemeinde-osterreich.at/) scraped und den dann auch als öffentlich Repo zur Verfügung stellen.

**Comment by bresu** [comment]
Sodale, habe die Daten bereinigt (händisch, gemeinde-oesterreich ist nicht up-to-date) und auch noch Wien in das "gemeindenJSON" gepackt. 
Sollten noch Fehler auftauchen, einfach einen Issue bei [meiner repo](https://github.com/bresu/oe_gemeinden/issues) machen :)

**Comment by cambid** [comment]
@bresu: Super, vielen Dank. Wir haben das gerade eingepflegt. Falls uns weitere Fehler auffallen, erstellen wir dir gerne ein Issue.
