### ISSUE TITLE
[mail] Referenzlink wirft 404

### ISSUE THREAD

**Issue by devNan0** [c3wien/Poke-That-Gmeind#123]
In [config/mail.py](https://github.com/c3wien/Poke-That-Gmeind/blob/dcd13ae1c75c140277e20bf132cba630a4412681/config/mail.py) wird als Referenz eine Seite der Stadtgemeinde Traiskirchen angegeben. Diese existiert jedoch nicht mehr und führ zu einen 404.
Ich habe geschaut ob sich vielleicht nur der Link geändert hat, konnte jedoch nichts mehr dazu auf der Seite von Traiskirchen finden.

https://github.com/c3wien/Poke-That-Gmeind/blob/dcd13ae1c75c140277e20bf132cba630a4412681/config/mail.py#L20

Potentielle alternative Referenz:
[Protokoll des Gemeinderates Traiskirchen vom 13.04.2021 (Seite 6)](https://www.traiskirchen.gv.at/fileadmin/files/download/pdfs/Kundmachungen/GR-Beschluesse_120421.pdf)

**Comment by cambid** [comment]
Korrekt wäre https://traiskirchen.gv.at/suche/virusbekaempfungs-luftreinigungsanlagen-in-allen-bildungseinrichtungen-traiskirchens/
