### ISSUE TITLE
Verlinkung zu Mastodon funktioniert nicht über DOH

### ISSUE THREAD

**Issue by mp-4** [c3wien/Poke-That-Gmeind#128]
Wenn man unter "Weitersagen" auf den Mastodon-Button klickt so bekommt man eine Fehlermeldung "Die Website ist nicht erreichbar".

Edit:
Nach kurzer Recherche hat sich herausgestellt, dass hier das DoH (DNS over HTTPS) Probleme macht.
Wird die Option in Chrome und Firefox deaktiviert, so lädt der besagt Link hinter dem Mastodon-Button.

**Comment by eest9** [comment]
Ich kann diese Einschätzung nicht nachvollziehen. In meinem Firefox habe ich hier keine Probleme.

**Comment by cambid** [comment]
As discussed in matrix. This isn't a problem with our projectsite but on the share-site we link (!) for to mastodon so I close this issue.
