### ISSUE TITLE
adapt landingpage

### ISSUE THREAD

**Issue by cambid** [c3wien/Poke-That-Gmeind#28]
the landingpage should be adapted from "Überwachungspaket" to "Luftfilterbegehren"

**Comment by pascoda** [comment]
in detail:
-     fancy header img? (if yes, needs to be smaller)
-     abstract (TLDR), followed by buttons for action: gemeinde + weitersagen (kinda like a flowchart)
-     drop everything else (yt-link, überwachungspaket contents, action items for politicians)

**Comment by pascoda** [comment]
should  be fixed in #38 (a monster of a pull request, I am sorry)

**Comment by pascoda** [comment]
header image has not been changed as of yet, so keeping this issue open.

**Comment by cambid** [comment]
A new header image will follow in #51
