### ISSUE TITLE
[gemeinde] add information on sending mail

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#37]
* unter "E-Mail senden:" Infotext, dass bitte alle Felder ausfüllen und Mailversand erst wenn Link in Validierungsmail geklickt wurde.
* "Deine E-Mail-Adresse" statt "E-Mail"
* schließendes Anführungszeichen fehlt bei "wenn gemeinde schon cmv hat"

**Comment by cambid** [comment]
This should be a change in the city.html
