### ISSUE TITLE
use correct contact for Vienna

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#4]
it's probably MA19, neither stadtschulrat nor bezirksvorstehung(en).

needs to be checked though:
https://www.wien.gv.at/stadtentwicklung/architektur/aufgaben.html

**Comment by cambid** [comment]
That can be fixed by modifying the cities.json

**Comment by pascoda** [comment]
we'll add a prefix "Wien" in front of the bezirksname.
all entries will have their respective zip code, but use the same www and email (that of MA19).
