### ISSUE TITLE
Fortschrittsbalken

### ISSUE THREAD

**Issue by eest9** [c3wien/Poke-That-Gmeind#44]
Aus UI Perspektive würde auf der Frontpage ein Fortschrittsbalken Sinn ergeben, der angibt wie viel Prozent der Gemeinden bereits das Begehren umgesetzt haben. Aus der UX-forschung wissen wir, dass solche Balken stark beim Engagement helfen.

Nicht Teil von #28 weil IMHO nur optional.

**Comment by cambid** [comment]
Die Idee gefällt mir. Darstellung in Prozent oder in absoluter Anzahl der Gemeinden oder beides?

Den Backend-Code dafür bekomm ich hin (Hint im __init__ von Cities und dazu ein paar Properties und eine neue Funktion für das Percentage) und die Darstellung bestimmt auch. Da gibt es bereits was in meinem lokalen Branch fortschrittsbalken-#44

**Comment by eest9** [comment]
Ich denke absolute Zahlen alla "x von y gemeinden haben dies umgesetzt" sollte reichen. Eventuell kann man für den Fortschrittsbalken einen Alt-Text in Prozent angeben, damit der relative Wert für Blinde und Sehbehinderte ebenfalls erkennbar ist? Jedoch gibt es das Alt-Attribut nur für img, area und input :/

**Comment by eest9** [comment]
Passt der Text? @pascoda? (ich denke beim counter das ganze in Prosa umschreiben und eventuell die Überschrift anders?)

Passt die Höhe des Balkens? @AshInformatics? IMHO könnte er schmaler sein.

**Comment by eest9** [comment]
Ich habe es mir noch einmal überlegt und eventuell sollte es in dieselbe `section` wie der Text, dann wird die Seite kürzer und darunter kommt dann der Pfeil, der dann die nächste Aktion ankündigt. Direkt unterm Balken dann ein Text wie `Bisher setzen 0 von 2117 Gemeinden Luftfilteranlagen in all ihren öffentlichen Gebäuden ein.`

**Comment by pascoda** [comment]
hab grad spontan nicht gefunden, wo der text rumfliegt. nachdem wir nicht prüfen, ob die gemeinden das *tatsächlich* tun, würde ich eher sagen:

`Bisher haben 0 von 2117 Gemeinden gemeldet, Luftfilteranlagen in öffentlichen Gebäuden einzusetzen oder das zu planen.`

**Comment by cambid** [comment]
Leiste gleich hoch wie Buttons.
Integration in die Section vorher und Text von Pascoda unten drunter.
