### ISSUE TITLE
provide tooltips in german

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#5]
should be self-explanatory, e.g. "please enter an email address" on /city.html

**Comment by eest9** [comment]
Ich sehe nicht wo der tooltip her kommt. Bei mir im Browser steht desweiteren schlicht "Bitte füllen Sie dieses Feld aus." Kann das aus dem Browser kommen? (hier Firefox)

**Comment by cambid** [comment]
The tooltips are provided by the browser natively in the language of the user.
