### ISSUE TITLE
new banner for landingpage

### ISSUE THREAD

**Issue by AshInformatics** [c3wien/Poke-That-Gmeind#51]
new banner for landingpage

**Comment by pascoda** [comment]
current size is 19something x 515 px, I'd like to have it about half as high -> 19something x 260 px.

**Comment by AshInformatics** [comment]
I need more time. I plead that we first take a cloud image from "unsplash" that matches the colour tone and that I trim a bit. Attached is the banner image, if someone else could please update it?

I have attached three examples. 

The size didn't really work out that way.
![banner_exp_1](https://user-images.githubusercontent.com/58686107/172151531-e6885ce5-2280-46ec-9ed0-3ded89a2cc50.jpg)
![banner_exp_2](https://user-images.githubusercontent.com/58686107/172151536-a01145fc-05f6-4f22-9df0-90b4fdb81259.jpg)
![banner_exp_3](https://user-images.githubusercontent.com/58686107/172151539-b8a30b4c-0e0e-4012-8250-7ea36e6ee7dd.jpg)

**Comment by pascoda** [comment]
proposal: just don't use a banner. it has no additional information value, and is only causing work (and stress) for us right now.
