### ISSUE TITLE
Wollen wir jetzt >du< oder >Sie<

### ISSUE THREAD

**Issue by eest9** [c3wien/Poke-That-Gmeind#62]
Wollen wir konsequent "du" oder "Sie" verwenden? Bisher wurde auf der Website überall "du", aber in den E-Mails "Sie" verwendet.

**Comment by cambid** [comment]
Beschluss: "Du" für die Benutzer\*innen und "Sie" für die Gemeinden.

**Comment by eest9** [comment]
Höfliches "Du" oder modernes "du"?

**Comment by cambid** [comment]
Ich bin für modernes, aber habe kein hartes Veto gegen ein höfliches.

**Comment by pascoda** [comment]
ich mach "du", weil "Du" ist sehr 2004.
