### ISSUE TITLE
Dinge, die so aufgefallen sind

### ISSUE THREAD

**Issue by mp-4** [c3wien/Poke-That-Gmeind#79]
Bei der Durchsicht der Website sind mir folgende Punkte aufgefallen:
 - Hauptseite:
   - Header -> "Luftfilterbegehren" schwebt ein bisschen zu hoch. (Im vergleich zu den Buttons "Weitersagen!", "Gemeinden anschreiben"!, usw.
   - Text - 1 - 2 Zeilenumbrüche wären nett
   - Text "In der Bundespolitik fehlt es an Plänen, Schulen, " - kommt da nach Plänen wirklich ein Beistrich? (Frage für einen Freund)
   - Text "Sie können selbst aktiv werden und Luftfilteranlagen installieren. " und "schreib jetzt deine Gemeinde an!" - maybe unterstreichen ?
   - Nach "Bisher haben 0 von 2117 ..." sollte ein Trennstrich oder sowas wie "Und Los geht's" stehen. (Hab am Anfang nicht gewusst warum da plötzlich ein gelber Pfeil kommt.)
  - "Gemeide Anschreiben":
    - Filter funktioniert - wäre aber noch schön wenn die Möglichkeiten in eine Reihe angezeigt werden und nicht "einfach" die anderen Möglichkeiten ausgeblendet werden. (Endloses Scrollen vermeiden)
    - Reihenfolge der Gemeinden scheinen willkührlich. Kann man die noch aufsteigend zählen lassen?
    - Die PLZ zu den Ortschaften/Gemeinden/Bezirke wäre denk ich auch ein Pluspunkt.*
    - Welche Bedeutung haben die gelben Felder ? Erschließt sich mir nicht ganz. (Ukraine Krieg?)

**Comment by pascoda** [comment]
- mobil sieht das Burgermenü sehr nach gr. Flagge aus 
- "In der Bundespolitik fehlt es an Plänen" -> ich hab (nach einem weinseeligen Familienessen, tbh) zuerst "in der Bundesrepublik" gelesen, d.h. ich würd vlt einfach ein „österreichischen“ vor Bundespolitik setzen?

**Comment by pascoda** [comment]
zwecks der gelben felder: wollen wir die gemeinde-kacheln vielleicht einfach einfärbig machen?

**Comment by pascoda** [comment]
alles entweder erledigt oder in eigene issues ausgelagert.
