### ISSUE TITLE
feature request: option for take-down 

### ISSUE THREAD

**Issue by pascoda** [c3wien/Poke-That-Gmeind#8]
provide description on how to get a community removed from the tool.

**where?** in FAQ and city detail view
**what?** "Falls Ihre Gemeinde bereits Luftfilter installiert hat, oder plant, dies zu tun, entfernen wir den Eintrag gerne aus dieser Plattform. Senden Sie uns dafür eine formlose Nachricht an <email>."

note: we could move these entries to a "hall of fame" (list of communities that already provide CMVs).

**Comment by cambid** [comment]
This should be a change in luftfilterbegehren/templates/general/faq.html and luftfilterbegehren/templates/act/city.html
